# Generated by Django 5.2.2 on 2025-06-04 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_acceso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombres', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('huella', models.BinaryField(blank=True, null=True)),
                ('nivel_acceso', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(default='planificacion', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_supervisados', to='access_control.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ControlDeIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado_salud_entrada', models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Regular', 'Regular'), ('Mal', 'Mal')], max_length=30, null=True)),
                ('estado_salud_Salida', models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Regular', 'Regular'), ('Mal', 'Mal')], max_length=30, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ingreso', to='access_control.proyecto')),
            ],
        ),
    ]
