# Generated by Django 5.2.2 on 2025-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controldeingreso',
            name='lugar_trabajo',
            field=models.CharField(blank=True, choices=[('Mina Norte', 'Mina Norte'), ('Mina Sur', 'Mina Sur'), ('Procesamiento', 'Procesamiento'), ('Administración', 'Administración'), ('Mantenimiento', 'Mantenimiento')], max_length=100, null=True),
        ),
    ]
